//! `brain compile`: generates/updates one wiki page per entity above a
//! centrality threshold, plus `index.md` and an appended `log.md` entry
//! — the deterministic half of the brain schema's Ingest Workflow, so
//! the AI only has to spend tokens on judgement (synthesis, flagging
//! contradictions in prose), not on filing.

use crate::frontmatter::{read_status, PageStatus};
use crate::page::build_page;
use brain_core::error::Result;
use brain_core::Entity;
use brain_store::Store;
use chrono::NaiveDate;
use std::collections::{BTreeMap, HashMap};
use std::path::Path;

/// Summary of one `compile` run.
#[derive(Debug, Default, Clone, Copy)]
pub struct CompileReport {
    /// Pages written or overwritten this run.
    pub written: usize,
    /// Pages left untouched because their on-disk `status` was `curated`.
    pub skipped_curated: usize,
    /// Total entities considered (above the centrality threshold).
    pub total_candidates: usize,
}

/// Regenerates `wiki_dir`'s pages for every entity at or above
/// `min_centrality`, then rewrites `index.md` and appends one line to
/// `log.md`. A page whose current on-disk `status:` frontmatter reads
/// `curated` is left alone — see [`crate::frontmatter`]'s docs.
pub fn compile(store: &Store, wiki_dir: &Path, min_centrality: f64) -> Result<CompileReport> {
    std::fs::create_dir_all(wiki_dir)?;
    let today = chrono::Utc::now().date_naive();

    // Dedup before filtering by centrality, not after: a bare
    // spell-list table entry can easily have *higher* centrality than
    // the real, specific entity it duplicates (see `dedup_by_slug`'s
    // docs), so filtering first could keep exactly the wrong one of the
    // pair even though the right one would otherwise have won.
    let mut entities = dedup_by_slug(store.list_entities(None)?);
    entities.retain(|e| e.centrality >= min_centrality);

    let mut report = CompileReport { total_candidates: entities.len(), ..Default::default() };
    let mut index_entries: Vec<(String, String, String)> = Vec::with_capacity(entities.len());

    for entity in &entities {
        let path = wiki_dir.join(format!("{}.md", entity.slug));
        match read_status(&path) {
            PageStatus::Curated => report.skipped_curated += 1,
            PageStatus::Generated => {
                let content = build_page(store, entity, today)?;
                std::fs::write(&path, content)?;
                report.written += 1;
            }
        }
        index_entries.push((entity.kind.as_str(), entity.slug.clone(), entity.name.clone()));
    }

    write_index(wiki_dir, &index_entries, today)?;
    append_log(wiki_dir, report.written, today)?;
    Ok(report)
}

/// Every wiki page's filename is its entity's slug, but two entities can
/// legitimately share a slug — a bare spell-list table entry recognized
/// only as a generic `"topic"`, alongside that same name's real, more
/// specific definition elsewhere in the corpus (the exact situation
/// [`brain_store::Store::find_entity_by_slug`] handles at lookup time).
/// Left alone, `compile` would write both to the same path, and
/// whichever happened to be processed last would silently clobber the
/// other. This keeps only the best entity per slug — a non-`"topic"`
/// kind always wins, centrality breaks any remaining tie — so every page
/// has one unambiguous, deterministic source, and sorts the result by
/// centrality, highest first.
fn dedup_by_slug(entities: Vec<Entity>) -> Vec<Entity> {
    let mut best: HashMap<String, Entity> = HashMap::new();
    for entity in entities {
        best.entry(entity.slug.clone())
            .and_modify(|existing| {
                let existing_is_topic = existing.kind.as_str() == "topic";
                let candidate_is_topic = entity.kind.as_str() == "topic";
                let candidate_wins = match (existing_is_topic, candidate_is_topic) {
                    (true, false) => true,
                    (false, true) => false,
                    _ => entity.centrality > existing.centrality,
                };
                if candidate_wins {
                    *existing = entity.clone();
                }
            })
            .or_insert(entity);
    }
    let mut out: Vec<Entity> = best.into_values().collect();
    out.sort_by(|a, b| b.centrality.partial_cmp(&a.centrality).unwrap());
    out
}

fn write_index(wiki_dir: &Path, entries: &[(String, String, String)], today: NaiveDate) -> Result<()> {
    let mut out = String::new();
    out.push_str("# Wiki Index\n\n");
    out.push_str(&format!("_Last updated: {today}_\n\n"));
    out.push_str("Generated by `brain compile`. Every page above the centrality threshold, by kind.\n\n");

    let mut by_kind: BTreeMap<&str, Vec<&(String, String, String)>> = BTreeMap::new();
    for entry in entries {
        by_kind.entry(entry.0.as_str()).or_default().push(entry);
    }
    for (kind, mut items) in by_kind {
        items.sort_by(|a, b| a.2.cmp(&b.2));
        out.push_str(&format!("## {}\n\n", title_case(kind)));
        for (_, slug, name) in items {
            out.push_str(&format!("- [[{slug}]] \u{2014} {name}\n"));
        }
        out.push('\n');
    }
    std::fs::write(wiki_dir.join("index.md"), out)?;
    Ok(())
}

fn append_log(wiki_dir: &Path, written: usize, today: NaiveDate) -> Result<()> {
    let path = wiki_dir.join("log.md");
    let mut content = std::fs::read_to_string(&path)
        .unwrap_or_else(|_| "# Wiki Log\n\nAppend-only record of all wiki activity.\n\n".to_string());
    content.push_str(&format!("## [{today}] compile | brain compile wrote/updated {written} pages\n"));
    std::fs::write(path, content)?;
    Ok(())
}

fn title_case(s: &str) -> String {
    let mut chars = s.chars();
    match chars.next() {
        Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
        None => String::new(),
    }
}
